--------------------------------------------------------------------------------
-- Script Oracle - Capa de eventos VetCare (DSY2207 - Semana 7, Formativa 5)
-- "Construyendo un sistema cloud con arquitectura basada en eventos"
--
-- Base: VeterinariaCloud (vetcloud, Oracle Autonomous DB, esquema ADMIN).
-- Se REUTILIZAN las tablas del sistema veterinario (no se modifican):
--   CLIENTES, MASCOTAS, EMPLEADOS, CITAS, COMUNICACIONES, INVENTARIO,
--   RESULTADOS_LABORATORIO
-- y se AGREGAN solo las tablas propias de la capa de eventos:
--   EVENTOS_LOG         -> event store / auditoria (RF5)       <- RegistrarEventoLog
--   EVENTOS_PROCESADOS  -> idempotencia + resultado por evento  <- ProcesarEventoClinico
--   NOTIFICACIONES      -> alertas internas (STOCK_BAJO)        <- ProcesarEventoClinico
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. EVENT STORE
--------------------------------------------------------------------------------
CREATE TABLE EVENTOS_LOG (
    ID_EVENTO       VARCHAR2(64)    NOT NULL,
    TIPO_EVENTO     VARCHAR2(100)   NOT NULL,
    SUBJECT         VARCHAR2(200),
    ORIGEN          VARCHAR2(400),
    FECHA_EVENTO    TIMESTAMP,
    FECHA_REGISTRO  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    PAYLOAD_JSON    CLOB,
    CONSTRAINT PK_EVENTOS_LOG PRIMARY KEY (ID_EVENTO),
    CONSTRAINT CK_EVENTOS_LOG_JSON CHECK (PAYLOAD_JSON IS JSON)
);

--------------------------------------------------------------------------------
-- 2. IDEMPOTENCIA / TRAZABILIDAD DE PROCESAMIENTO
--    Un evento de negocio se procesa una sola vez (PK = id del evento de Event Grid).
--    REFERENCIA = id de negocio del evento (TUR-XXXXXXXX, ITEM-n, LAB-XXXXXXXX).
--    ID_CITA    = cita creada por un TurnoAgendado (permite cancelar por TUR-...).
--    RESULTADO  = OK: ... | RECHAZADO: ... (mascota inexistente, sin stock, etc.)
--------------------------------------------------------------------------------
CREATE TABLE EVENTOS_PROCESADOS (
    ID_EVENTO       VARCHAR2(64)    NOT NULL,
    TIPO_EVENTO     VARCHAR2(100)   NOT NULL,
    REFERENCIA      VARCHAR2(40),
    ID_CITA         NUMBER,
    RESULTADO       VARCHAR2(300),
    FECHA_PROCESO   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EVENTOS_PROCESADOS PRIMARY KEY (ID_EVENTO)
);
CREATE INDEX IX_EVPROC_REFERENCIA ON EVENTOS_PROCESADOS (REFERENCIA);

--------------------------------------------------------------------------------
-- 3. ALERTAS INTERNAS (stock bajo)
--------------------------------------------------------------------------------
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_EVENTO         VARCHAR2(64)    NOT NULL,
    TIPO              VARCHAR2(30)    NOT NULL,
    DESTINATARIO      VARCHAR2(150)   NOT NULL,
    MENSAJE           VARCHAR2(500)   NOT NULL,
    FECHA_PROGRAMADA  TIMESTAMP       NOT NULL,
    ESTADO            VARCHAR2(20)    DEFAULT 'PENDIENTE' NOT NULL,
    REFERENCIA        VARCHAR2(40),
    CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY (ID_NOTIFICACION),
    CONSTRAINT UQ_NOTIF_EVENTO_TIPO UNIQUE (ID_EVENTO, TIPO),
    CONSTRAINT CK_NOTIF_TIPO CHECK (TIPO IN ('RECORDATORIO_TURNO', 'RESULTADO_LAB', 'STOCK_BAJO')),
    CONSTRAINT CK_NOTIF_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'ENVIADA', 'CANCELADA'))
);

--------------------------------------------------------------------------------
-- 4. DATOS DE APOYO PARA LA DEMO (en tablas existentes del sistema veterinario)
--    CITAS.ID_VETERINARIO es FK a EMPLEADOS: se necesita al menos un veterinario.
--------------------------------------------------------------------------------
INSERT INTO EMPLEADOS (RUT, NOMBRE, APELLIDO, CARGO, EMAIL, TELEFONO, ACTIVO)
VALUES ('12345678-5', 'Camila', 'Rojas', 'VETERINARIO', 'camila.rojas@vetcare.cl', '+56911112222', 1);

INSERT INTO INVENTARIO (NOMBRE, TIPO, UNIDAD_MEDIDA, STOCK_ACTUAL, STOCK_MINIMO, PROVEEDOR)
VALUES ('Antiparasitario interno 10 kg', 'MEDICAMENTO', 'COMPRIMIDO', 20, 5, 'Drag Pharma');
INSERT INTO INVENTARIO (NOMBRE, TIPO, UNIDAD_MEDIDA, STOCK_ACTUAL, STOCK_MINIMO, PROVEEDOR)
VALUES ('Meloxicam 1.5 mg/ml', 'MEDICAMENTO', 'FRASCO', 6, 5, 'Boehringer');
COMMIT;

--------------------------------------------------------------------------------
-- 5. CONSULTAS DE VERIFICACION (para el video)
--------------------------------------------------------------------------------
-- SELECT * FROM EVENTOS_PROCESADOS ORDER BY FECHA_PROCESO DESC;
-- SELECT * FROM CITAS ORDER BY ID_CITA DESC;
-- SELECT * FROM COMUNICACIONES ORDER BY ID_COMUNICACION DESC;
-- SELECT * FROM INVENTARIO ORDER BY ID_ITEM;
-- SELECT * FROM RESULTADOS_LABORATORIO ORDER BY ID_RESULTADO DESC;
-- SELECT * FROM NOTIFICACIONES ORDER BY ID_NOTIFICACION DESC;
-- SELECT ID_EVENTO, TIPO_EVENTO, SUBJECT, FECHA_REGISTRO FROM EVENTOS_LOG ORDER BY FECHA_REGISTRO DESC;
