--------------------------------------------------------------------------------
-- DSY2207 - Semana 8 - Actividad Sumativa 3
-- "Aplicando tecnologias de eventos en arquitecturas cloud"
-- Sistema de Gestion de Usuarios y Roles + Azure Event Grid
--
-- Ejecutar en la base Oracle "usuariosroles" (OCI), esquema ADMIN, la misma
-- que usan function-usuarios y function-roles. Solo AGREGA tablas: no modifica
-- USUARIOS ni ROLES. Prefijo UR_ para no chocar con tablas de otras actividades.
--------------------------------------------------------------------------------

-- Limpieza (solo si se necesita recrear)
-- DROP TABLE UR_NOTIFICACIONES PURGE;
-- DROP TABLE UR_EVENTOS_PROCESADOS PURGE;
-- DROP TABLE UR_AUDITORIA_EVENTOS PURGE;

-- 1. Auditoria: TODOS los eventos del topic (suscripcion sub-auditoria, sin filtro)
CREATE TABLE UR_AUDITORIA_EVENTOS (
    ID_EVENTO       VARCHAR2(64)    NOT NULL,
    TIPO_EVENTO     VARCHAR2(100)   NOT NULL,
    SUBJECT         VARCHAR2(200),
    FECHA_EVENTO    TIMESTAMP,
    FECHA_REGISTRO  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    PAYLOAD_JSON    CLOB,
    CONSTRAINT PK_UR_AUDITORIA PRIMARY KEY (ID_EVENTO)
);

-- 2. Idempotencia: un evento se procesa una sola vez por consumidor
CREATE TABLE UR_EVENTOS_PROCESADOS (
    ID_EVENTO       VARCHAR2(64)    NOT NULL,
    CONSUMIDOR      VARCHAR2(60)    NOT NULL,
    TIPO_EVENTO     VARCHAR2(100)   NOT NULL,
    SUBJECT         VARCHAR2(200),
    RESULTADO       VARCHAR2(20)    NOT NULL,
    DETALLE         VARCHAR2(500),
    FECHA_PROCESO   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_UR_PROCESADOS PRIMARY KEY (ID_EVENTO, CONSUMIDOR),
    CONSTRAINT CK_UR_PROCESADOS_RES CHECK (RESULTADO IN ('EN_PROCESO', 'PROCESADO', 'SIN_ACCION', 'RECHAZADO'))
);

-- 3. Notificaciones generadas por las consumidoras (sin FK a USUARIOS: la
--    notificacion de BAJA se guarda aunque el usuario ya no exista)
CREATE TABLE UR_NOTIFICACIONES (
    ID_NOTIFICACION NUMBER(10)      GENERATED BY DEFAULT AS IDENTITY,
    ID_USUARIO      NUMBER(10)      NOT NULL,
    ID_EVENTO       VARCHAR2(64)    NOT NULL,
    TIPO            VARCHAR2(30)    NOT NULL,
    MENSAJE         VARCHAR2(500)   NOT NULL,
    FECHA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_UR_NOTIFICACIONES PRIMARY KEY (ID_NOTIFICACION),
    CONSTRAINT CK_UR_NOTIF_TIPO CHECK (TIPO IN ('BIENVENIDA', 'ROL_ASIGNADO', 'CAMBIO_ROL', 'BAJA',
                                                'REASIGNACION_ROL', 'ROL_RENOMBRADO'))
);
CREATE INDEX IX_UR_NOTIF_USUARIO ON UR_NOTIFICACIONES (ID_USUARIO);

-- 4. El rol por defecto (App Setting ROL_POR_DEFECTO) debe existir.
--    Si ya existe 'CONSULTA' este INSERT no hace nada.
INSERT INTO ROLES (NOMBRE_ROL)
SELECT 'CONSULTA' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE UPPER(NOMBRE_ROL) = 'CONSULTA');

COMMIT;

-- Verificacion
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'UR\_%' ESCAPE '\' ORDER BY TABLE_NAME;
SELECT ID_ROL, NOMBRE_ROL FROM ROLES ORDER BY ID_ROL;
